
POST http://localhost:3000/api/greet
Content-Type: 'application/json'

{
    "sender": "Bob",
    "message": "testitervehdys"
}

###

GET http://localhost:3000

###

DELETE http://localhost:3000/api/resource/99

###

GET http://localhost:3000/api/ero/2/7

###

GET http://localhost:3000/public/test-css.css

###

GET http://localhost:3000/api/items

###

DELETE http://localhost:3000/api/items/3

###

POST http://localhost:3000/api/items
Content-Type: application/json

{
    "nane": "Sitruuna"
}

###

PUT http://localhost:3000/api/items/3
Content-Type: application/json

{
    "name": "Patrick"
}


### items

### get all items

GET http://localhost:3000/api/users/

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "username": "Uusi käyttäjä",
    "password": "salakana",
    "email": "newuser@example.com"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "Uusi käyttäjä",
    "password": "salakana"
}

###

GET http://localhost:3000/api/users/5

###

PUT http://localhost:3000/api/users/2
Content-Type: application/json

{
    "password": "NEWPASS"
}

###

DELETE http://localhost:3000/api/users/2